'''
Jovienne Trotta
CS 5001 | Fall 2022
Lab 2: Crypto Currency Conversion

During this second lab we created a currency converter tool.
This allows users to convert between USD, BitCoin, and Ethereum.
This will also draw the logo users are converting TO using Python turtle. 
''' 

from turtle import *

#constant for Bitcoin logo
SCALE = .75

#these are the conversion rates for 9/21/22
USD_TO_BITCOIN = 0.000054
USD_TO_ETHEREUM = 0.00080
BITCOIN_TO_USD = 18459.50
BITCOIN_TO_ETHEREUM = 14.69
ETHEREUM_TO_USD = 1253.02
ETHEREUM_TO_BITCOIN = 0.068

def main():

    #user enters $$$ to convert from one currency to another
    #if an invalid value is entered the program will keep asking until we get a number
    while True: #while loops run until condition becomes false, a while true loop will run forever
        try:
            currency_amount = float(input("Please enter a currency amount: ")) #wrong type will trigger value error
        except ValueError: #if they enter a string that will trigger a value error, which will tell the user what they did wrong
            print("You need to enter a number.")
            continue #so it will return to the beginning of the while loop, and keep asking for a float
        else:
            break

    #user enters the currency they are converting from
    currency_in = input("Amount entered is in what form? \nPlease enter: \n...'1' for USD \n...'2' for Bitcoin \n...'3' for Ethereum \n: ")
    if currency_in == "one" or currency_in == "1":
        print("Thanks! You are converting from USD.")
    elif currency_in == "two" or currency_in == "2":
        print("Thanks! You are converting from Bitcoin.")
    elif currency_in == "three" or currency_in == "3":
        print("Thanks! You are converting from Ethereum.")
    else:
        print("Sorry! That's not an option. Please enter 1, 2, or 3.")
        exit()

    #user enters the currency they are converting to
    convert_to = input("Convert the entered amount to what form? \nPlease enter: \n...'1' for USD \n...'2' for Bitcoin \n...'3' for Ethereum \n: ")
    if convert_to == "one" or convert_to == "1":
        print("Thanks! You are converting to USD.")
    elif convert_to == "two" or convert_to == "2":
        print("Thanks! You are converting to Bitcoin.")
    elif convert_to == "three" or convert_to == "3":
        print("Thanks! You are converting to Ethereum.")
    else:
        print("Sorry! That's not an option. Please enter 1, 2, or 3.")
        exit()

    #the next section converts currency_in to convert_to
    #USD TO USD
    if (currency_in == "1" or currency_in == "one") and (convert_to == "1" or convert_to == "one"):
        final_amount = str(currency_amount)
        print(str(currency_amount) + " USD is " + final_amount + " USD")

        #this will create the US dollar sign
        fillcolor("green")
        begin_fill()
        forward(90)
        right(90)
        forward(60)
        right(90)
        forward(30)
        right(90)
        forward(30)
        left(90)
        forward(60)
        left(90)
        forward(60)
        left(90)
        forward(90)
        right(90)
        forward(120)
        right(90)
        forward(120)
        right(90)
        forward(60)
        right(90)
        forward(30)
        right(90)
        forward(30)
        left(90)
        forward(60)
        left(90)
        forward(60)
        left(90)
        forward(90)
        right(90)
        forward(120)
        right(90)
        forward(30)
        end_fill()
        fillcolor("black")
        begin_fill()
        left(90)
        forward(30)
        right(90)
        forward(10)
        right(90)
        forward(270)
        right(90)
        forward(10)
        right(90)
        forward(270)
        end_fill()
        up()
        right(90)
        forward(50)
        down()
        begin_fill()
        forward(10)
        right(90)
        forward(270)
        right(90)
        forward(10)
        right(90)
        forward(270)
        end_fill()
        mainloop()

    #BITCOIN TO BITCOIN
    elif (currency_in == "2" or currency_in == "two") and (convert_to == "2" or convert_to == "two"):
        final_amount = str(currency_amount)
        print(str(currency_amount) + " Bitcoin is " + final_amount + " Bitcoin")
        
        #this will create the Bitcoin logo
        up()
        right(90)
        forward(150)
        left(90)
        down()
        fillcolor("orange")
        begin_fill()
        circle(200)
        end_fill()
        fillcolor("white")
        up()
        left(90)
        forward(60)
        right(90)
        forward(30)
        (down)
        begin_fill()
        circle(80,180)
        right(180)
        circle(60,180)
        forward(120)
        left(90)
        forward(30)
        left(90)
        forward(30)
        right(90)
        forward(220)
        right(90)
        forward(30)
        left(90)
        forward(30)
        left(90)
        forward(60)
        end_fill()
        up()
        left(90)
        forward(40)
        right(90)
        forward(20)
        down()
        fillcolor("orange")
        color("orange")
        begin_fill()
        circle(80*SCALE,180)
        right(180)
        circle(60*SCALE,180)
        left(90)
        forward(220)
        end_fill()
        mainloop()

    #ETHEREUM TO ETHEREUM
    elif (currency_in == "3" or currency_in == "three") and (convert_to == "3" or convert_to == "three"):
        final_amount = str(currency_amount)
        print(str(currency_amount) + " Ethereum is " + final_amount + " Ethereum")

        #this will create the Ethereum logo
        fillcolor("black")
        begin_fill()
        left(20)
        forward(100)
        left(140)
        forward(100)
        left(40)
        forward(100)
        left(140)
        forward(100)
        end_fill()
        fillcolor("grey")
        up()
        left(40)
        forward(110)
        down()
        begin_fill()
        left(140)
        forward(110)
        left(40)
        forward(110)
        right(160)
        forward(130)
        right(78)
        forward(135)
        end_fill()
        up()
        forward(20)
        down()
        begin_fill()
        right(85)
        forward(220)
        right(115)
        forward(220)
        right(150)
        forward(140)
        left(60)
        forward(140)
        end_fill()
        mainloop()

    #USD TO BITCOIN
    elif (currency_in == "1" or currency_in == "one") and (convert_to == "2" or convert_to == "two"):
        final_amount = str(currency_amount * USD_TO_BITCOIN)
        print(str(currency_amount) + " USD is " + final_amount + " Bitcoin")

        #this will create the Bitcoin logo
        up()
        right(90)
        forward(150)
        left(90)
        down()
        fillcolor("orange")
        begin_fill()
        circle(200)
        end_fill()
        fillcolor("white")
        up()
        left(90)
        forward(60)
        right(90)
        forward(30)
        (down)
        begin_fill()
        circle(80,180)
        right(180)
        circle(60,180)
        forward(120)
        left(90)
        forward(30)
        left(90)
        forward(30)
        right(90)
        forward(220)
        right(90)
        forward(30)
        left(90)
        forward(30)
        left(90)
        forward(60)
        end_fill()
        up()
        left(90)
        forward(40)
        right(90)
        forward(20)
        down()
        fillcolor("orange")
        color("orange")
        begin_fill()
        circle(80*SCALE,180)
        right(180)
        circle(60*SCALE,180)
        left(90)
        forward(220)
        end_fill()
        mainloop()

    #USD TO ETHEREUM
    elif (currency_in == "1" or currency_in == "one") and (convert_to == "3" or convert_to == "three"):
        final_amount = str(currency_amount * USD_TO_ETHEREUM)
        print(str(currency_amount) + " USD is " + final_amount + " Ethereum")

        #this will create the Ethereum logo
        fillcolor("black")
        begin_fill()
        left(20)
        forward(100)
        left(140)
        forward(100)
        left(40)
        forward(100)
        left(140)
        forward(100)
        end_fill()
        fillcolor("grey")
        up()
        left(40)
        forward(110)
        down()
        begin_fill()
        left(140)
        forward(110)
        left(40)
        forward(110)
        right(160)
        forward(130)
        right(78)
        forward(135)
        end_fill()
        up()
        forward(20)
        down()
        begin_fill()
        right(85)
        forward(220)
        right(115)
        forward(220)
        right(150)
        forward(140)
        left(60)
        forward(140)
        end_fill()
        mainloop()

    #BITCOIN TO USD
    elif (currency_in == "2" or currency_in == "two") and (convert_to == "1" or convert_to == "one"):
        final_amount = str(currency_amount * BITCOIN_TO_USD)
        print(str(currency_amount) + " Bitcoin is " + final_amount + " USD")

        #this will create the US dollar sign
        fillcolor("green")
        begin_fill()
        forward(90)
        right(90)
        forward(60)
        right(90)
        forward(30)
        right(90)
        forward(30)
        left(90)
        forward(60)
        left(90)
        forward(60)
        left(90)
        forward(90)
        right(90)
        forward(120)
        right(90)
        forward(120)
        right(90)
        forward(60)
        right(90)
        forward(30)
        right(90)
        forward(30)
        left(90)
        forward(60)
        left(90)
        forward(60)
        left(90)
        forward(90)
        right(90)
        forward(120)
        right(90)
        forward(30)
        end_fill()
        fillcolor("black")
        begin_fill()
        left(90)
        forward(30)
        right(90)
        forward(10)
        right(90)
        forward(270)
        right(90)
        forward(10)
        right(90)
        forward(270)
        end_fill()
        up()
        right(90)
        forward(50)
        down()
        begin_fill()
        forward(10)
        right(90)
        forward(270)
        right(90)
        forward(10)
        right(90)
        forward(270)
        end_fill()
        mainloop()

    #BITCOIN TO ETHEREUM
    elif (currency_in == "2" or currency_in == "two") and (convert_to == "3" or convert_to == "three"):
        final_amount = str(currency_amount * BITCOIN_TO_ETHEREUM)
        print(str(currency_amount) + " Bitcoin is " + final_amount + " Ethereum")

        #this will create the Ethereum logo
        fillcolor("black")
        begin_fill()
        left(20)
        forward(100)
        left(140)
        forward(100)
        left(40)
        forward(100)
        left(140)
        forward(100)
        end_fill()
        fillcolor("grey")
        up()
        left(40)
        forward(110)
        down()
        begin_fill()
        left(140)
        forward(110)
        left(40)
        forward(110)
        right(160)
        forward(130)
        right(78)
        forward(135)
        end_fill()
        up()
        forward(20)
        down()
        begin_fill()
        right(85)
        forward(220)
        right(115)
        forward(220)
        right(150)
        forward(140)
        left(60)
        forward(140)
        end_fill()
        mainloop()

    #ETHEREUM TO USD
    elif (currency_in == "3" or currency_in == "three") and (convert_to == "1" or convert_to == "one"):
        final_amount = str(currency_amount * ETHEREUM_TO_USD)
        print(str(currency_amount) + " Ethereum is " + final_amount + " USD")

        #this will create the US dollar sign
        fillcolor("green")
        begin_fill()
        forward(90)
        right(90)
        forward(60)
        right(90)
        forward(30)
        right(90)
        forward(30)
        left(90)
        forward(60)
        left(90)
        forward(60)
        left(90)
        forward(90)
        right(90)
        forward(120)
        right(90)
        forward(120)
        right(90)
        forward(60)
        right(90)
        forward(30)
        right(90)
        forward(30)
        left(90)
        forward(60)
        left(90)
        forward(60)
        left(90)
        forward(90)
        right(90)
        forward(120)
        right(90)
        forward(30)
        end_fill()
        fillcolor("black")
        begin_fill()
        left(90)
        forward(30)
        right(90)
        forward(10)
        right(90)
        forward(270)
        right(90)
        forward(10)
        right(90)
        forward(270)
        end_fill()
        up()
        right(90)
        forward(50)
        down()
        begin_fill()
        forward(10)
        right(90)
        forward(270)
        right(90)
        forward(10)
        right(90)
        forward(270)
        end_fill()
        mainloop()

    #ETHEREUM TO BITCOIN
    elif (currency_in == "3" or currency_in == "three") and (convert_to == "2" or convert_to == "two"):
        final_amount = str(currency_amount * ETHEREUM_TO_BITCOIN)
        print(str(currency_amount) + " Ethereum is " + final_amount + " Bitcoin")

        #this will create the Bitcoin logo
        up()
        right(90)
        forward(150)
        left(90)
        down()
        fillcolor("orange")
        begin_fill()
        circle(200)
        end_fill()
        fillcolor("white")
        up()
        left(90)
        forward(60)
        right(90)
        forward(30)
        (down)
        begin_fill()
        circle(80,180)
        right(180)
        circle(60,180)
        forward(120)
        left(90)
        forward(30)
        left(90)
        forward(30)
        right(90)
        forward(220)
        right(90)
        forward(30)
        left(90)
        forward(30)
        left(90)
        forward(60)
        end_fill()
        up()
        left(90)
        forward(40)
        right(90)
        forward(20)
        down()
        fillcolor("orange")
        color("orange")
        begin_fill()
        circle(80*SCALE,180)
        right(180)
        circle(60*SCALE,180)
        left(90)
        forward(220)
        end_fill()
        mainloop()

    else:
        exit()

main()
    